# This is a basic workflow that is manually triggered

name: SSH Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd / 
          cd opt
          cd bitnami
          cd projects
          cd Innkeeper
          git pull
          kill -KILL $(pgrep -a 'node' | grep Innkeeper | awk '{print $1}')
          forever start dist/index.js
